# Generated by Django 5.1.1 on 2024-09-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='video_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='queries',
            name='query',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
